### PR TITLE
Add a changelog.

### PR DESCRIPTION
**Pull request by blimmer**
It's hard to know when to upgrade. This is a changelog generated [by this gem](https://github.com/skywinder/github-changelog-generator).

### CODE REVIEW

**Comment by trek** [comment]
Not sure an autogenerated changelog is useful. Many of the issues and PRs have no meaning for consumers of this library.

**Comment by blimmer** [comment]
I've been waiting for [host support](https://github.com/pretenderjs/pretender/pull/91/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR28) and I had to dig through to see if it's done. Idk, feel free to close, but I think all public projects should have a changelog or release notes.

**Comment by trek** [comment]
I'm down for changelogs, but the autogenerated ones seem more noise than anything.

**Comment by blimmer** [comment]
Opened #93 to track this.

**Pull request closed without merging**
