### PR TITLE
Passthrough: fixes #121

### LINKED ISSUE #121: passthrough and phantomjs regression in 0.10.1 vs 0.10.0
I'm using pretender with ember-cli-blanket.  I have this in my fixtures so that the code coverage report won't be intercepted:

```
this.post('/write-blanket-coverage', this.passthrough);
```

I was running 0.10.0, and the coverage report was working fine in both the browser and command line.  

I updated to 0.10.1, and it worked fine in the browser but the coverage report was not written when running on the command line with phantomjs (1.9.8).  

I had trouble with this before, which I think was related to this: https://github.com/pretenderjs/pretender/pull/76 (and updating to 0.10.0 fixed it).

### PR DESCRIPTION
**Pull request by sudrao**

### CODE REVIEW

**Comment by john-kurkowski** [comment]
Commenting to link ticket #121

**Comment by john-kurkowski** [comment]
Not sure what happened with the PR's Travis CI build, but this fix worked for me!

**Comment by fotinakis** [comment]
Would love to see this refreshed and merged, I believe it is affecting certain cases of ember-cli-mirage usage.

**Comment by sudrao** [comment]
@trek Tests pass now. Please merge after review.

**Comment by wagenet** [comment]
From my analysis, this isn't really a problem with Pretender. Pretender isn't designed to have multiple instances running at once and `shutdown` should be called on the previous instance before starting a new one. However, in ember-cli-mirage 0.1.x, `shutdown` was not called when it should have been (this is fixed in 0.2). After talking with @trek, I think the correct solution here is to warn (or error) when a second instance is being started while one is still active. Attempting to make multiple instances of Pretender run at once probably involves more thorough work than this PR.

**Comment by trek** [comment]
Closing based on @wagenet's description. A total side note: without tests and a description, I don't think this PR would have been accepted.

**Comment by trek** [comment]
See https://github.com/pretenderjs/pretender/pull/165 for an implementation like @wagenet suggested

**Comment by john-kurkowski** [comment]
Should the conclusions in this thread be carried over to the issue this was supposed to fix, #121? Is #121 closed then?

**Pull request closed without merging**
