### PR TITLE
Added json helper to Pretender

### PR DESCRIPTION
**Pull request by taras**
- Added Pretender.json() helper
- Added tests for json helper
- Added docs to README about json helper

PR created on @stefanpenner's recommendation

### CODE REVIEW

**Comment by stefanpenner** [comment]
ya, i found this little helper made worlds of difference in readability to my pretender code.

https://github.com/stefanpenner/ember-jobs/blob/master/tests/acceptance/posting-test.js#L26-L39

**Comment by trek** [comment]
How is this different than/interacts with configuring your pretender server with `prepareBody` and `prepareHeaders`?

**Comment by stefanpenner** [comment]
I tried that, this seemed to click more for me. So maybe this personal preference?

**Comment by truenorth** [comment]
This would be lovely :+1:

**Comment by stefanpenner** [comment]
rebased https://github.com/pretenderjs/pretender/pull/104

**Pull request closed without merging**
