### PR TITLE
don’t leak passthroughRequests

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by stefanpenner** [comment]
@mike-north / @trek  r?

**Comment by samselikoff** [comment]
Wondering if we should add the config option, this has been requested for all tracked requests: https://github.com/pretenderjs/pretender/pull/141/files

**Comment by stefanpenner** [comment]
@samselikoff can you share when the above array is used? I'm not familiar with usages, but i could imagine it is.

**Comment by samselikoff** [comment]
@stefanpenner I don't think it is (someone could always be diving in), my point was just that we should add the option for the other types too since they were causing memory problems for mirage users. We can merge this in though.

**Comment by stefanpenner** [comment]
@samselikoff oh, I see. You raise a good point. Thoughts on maybe making it opt-int for those arrays ?

**Comment by samselikoff** [comment]
yep opt-in sounds right

**Comment by trek** [comment]
I think we need to keep this as-is unless we want to do a version bump. This doesn't "leak" in the sense that Pretender _is_ intended to track these during a run. I could see adding behavior in `shutdown` if the concern is that a reference to a pretender instance remains in some other code and so references to these requests are also retained.

Correct me if I'm wrong, but it seems the underlying issues is tension between how often Pretender was intended to refresh state (before/after each test) and how Mirage would like to use Pretender (long-running, and thus susceptible to an every-growing set of bookkeeping objects).

If _that_ is the case, I think we need allow, as you suggest, the _option_ to track requests. For the current version it would need to be opt-out, but we could move to opt-in for a future version, depending how what seems to be the most typical case.

**Comment by samselikoff** [comment]
Yes - I agree, and you're correct we should make it opt-out, to preserve Pretender's existing behavior and introduce no breaking changes.

**Comment by stefanpenner** [comment]
> Correct me if I'm wrong, but it seems the underlying issues is tension between how often Pretender was intended to refresh state (before/after each test) and how Mirage would like to use Pretender (long-running, and thus susceptible to an every-growing set of bookkeeping objects).

Yup.



> If that is the case, I think we need allow, as you suggest, the option to track requests. For the current version it would need to be opt-out, but we could move to opt-in for a future version, depending how what seems to be the most typical case.

It seems like opt-out is fine, is it worth changing it as a default in the future or can something like mirage always flip the switch correctly?

**Comment by samselikoff** [comment]
@stefanpenner want some help with this?

**Comment by stefanpenner** [comment]
I think the caller of pretender should recycle pretender instance between tests. I don't think this needs to change.

**Pull request closed without merging**
