### PR TITLE
Update pretender.js

### LINKED ISSUE #85: jQuery 1.x with passthrough
I can't get passthrough to work with jQuery 1.x. The requests are sent using `$.ajax('/path').then(...)` but the `then` callbacks are never fired.

Seems like the `onload` event is detected on the browser `xhr` but is not supported by the 1.x jQuery [`xhr`](https://github.com/jquery/jquery/blob/1.11.3/src/ajax/xhr.js) module, so it is not [dispatched](https://github.com/pretenderjs/pretender/blob/053b865064cf09dc6a07800b7a5039880381a8df/pretender.js#L168) when the response is received.

I was able to get the events to fire by removing the check for [`onload`](https://github.com/pretenderjs/pretender/blob/053b865064cf09dc6a07800b7a5039880381a8df/pretender.js#L143) and just adding both events. 

There is a chance that both events could be fired I'm guessing. Any other concerns I should check into before getting a PR ready?

### PR DESCRIPTION
**Pull request by olivierlesnicki**
fix #85

### CODE REVIEW

**Comment by trek** [comment]
Can you check my CI is failing?

**Comment by thijsvdanker** [comment]
CI was failing because extracting FakeXMLHttpRequest gave an error
```
bower invalid-meta  fake-xml-http-request is missing "ignore" entry in bower.json
```
And pretender.js fails when requiring 'fake-xml-http-request'.

I was having issues with callbacks not being called as well, even when using jQuery 2.x.
Using @olivierlesnicki PR fixed the issue for me, but I have too little knowledge of the internals to say if it's good.

**Comment by thijsvdanker** [comment]
@trek Can you run CI again to see if it was indeed a hickup?

**Comment by olivierlesnicki** [comment]
@thijsvdanker I've triggered the CI again

**Comment by trek** [comment]
CI is still failing, sadly.

**Comment by thijsvdanker** [comment]
This time CI actually fails because of the patch. I can reproduce the failing test with running `npm test` locally.
Reverting the patch makes the test pass again.

**Comment by john-kurkowski** [comment]
Should this be closed in favor of #130? Fixes the same issue, performs refactoring, tests pass. All it needs is to add jQuery 1.x to the test suite.

**Comment by olivierlesnicki** [comment]
@john-kurkowski agreed

**Comment by trek** [comment]
Closing in favor of #130

**Pull request closed without merging**
