### PR TITLE
Added json helper to Pretender

### PR DESCRIPTION
**Pull request by stefanpenner**
- Added Pretender.json() helper
- Added tests for json helper
- Added docs to README about json helper

PR created on @stefanpenner's recommendation

### CODE REVIEW

**Comment by trek** [comment]
Still not a huge fan, although this is a common case. How would I add more headers when I need them?

The foundational problem here (mutating requests on the way in and and responses on the a way out) seems better handled via the middleware approach #70.

A middleware could allow an entire server to use a custom public API for return values in the responder by exposing the normal api to the framework's internals.

**Comment by stefanpenner** [comment]
> How would I add more headers when I need them?

In-practice this seems rare, or could be added via a middleware/preprocess hook.

The most common use-case seems to be:

* JSON response, with some status code

before:
```js
server.get('path', function() {
  return [200, { "Content-Type': "application/json" }, JSON.stringify({})]
});
```

after:

```js
server.get('path', json(200, {}));
```

If users need custom headers on a specific request, they can peel back the JSON sugar and :shipit:

**Comment by DingoEatingFuzz** [comment]
Seems like if you are going to add a json helper, you are opening the floodgates to any number of other helpers.

I also really don't like the opinion of other headers being uncommon. It's a good hunch, but it's still an opinion leaking in.

I have handled this, for the specific APIs I have to deal with, with a catchall approach:

```js
api.prepareHeaders = function(headers) {
  headers['content-type'] = 'application/json';
  return headers;
};

api.prepareBody = function(body) {
  return JSON.stringify(body || {});
};
```

I have also written a large number of helper functions for composing handlers. Here are a few.

```js
this.get('/api/account', relatedAccounts('account1'));
this.get('/api/account/:id', one('accounts'));
this.get('/api/account/all', all('accounts', 'account_id'));
this.get('/api/auth', allOrOne('auths'));
this.post('/api/auth', mustPatch());
this.delete('/api/segment/:id', noResponse());
```

The `one`, `all`, and `allOrOne` helpers all integrate with our fixtures, `mustPatch` throws if there is isn't a patch provided for the route (patching is another system we have), and `noResponse` is actually reusable. 

Here are a couple of the definitions for reusable helpers.

```js
export function empty() {
  return patchableResponder(function(req) {
    return ok({ });
  });
}

export function noResponse() {
  return patchableResponder(function(req) {
    return noContent();
  });
}
```

Here `ok` and `noContent` are helpers for building envelopes:

```js
function ok() {
  return [ 200, {} ].concat([].slice.call(arguments));
}

function noContent() {
  return [ 204, {} ];
}
```

I don't think any of this stuff should end up in Pretender, but hopefully this serves as some food for thought.

There is more than one way to go about building out these helpers, and I think those opinions should come from some other project.

**Comment by trek** [comment]
If we lived in a world with great package managers I'd just say we want another library that provides common helpers for specific common cases, like authoring a json api. This can easily live within the pretenderjs org

```
import Pretender from "pretender";
import {json, ok} from "pretender-json-api";

let server = new Pretender(function(){
  this.get('/all/songs', function(req){
    let myObject = {
      key: 'val'
    };
    
    return ok(json(myObject))
  })
});
```

**Comment by cibernox** [comment]
I'm going to lure @samselikoff here as someone that builds on top predender and has actually already built a DSL to make it nicer to use.

**Comment by stefanpenner** [comment]
> I also really don't like the opinion of other headers being uncommon. It's a good hunch, but it's still an opinion leaking in.
> 
> I have handled this, for the specific APIs I have to deal with, with a catchall approach:

you example is also the solution i suggest

**Comment by DingoEatingFuzz** [comment]
> the basic JSON case is by far the most common. Nothing prevents apps users from taking the approach and having there own helpers to cleanup code.

Definitely the most common, and it wouldn't be the end of the world if this got merged.

> opinions guide an ecosystem

Fair point, still doesn't mean they need to be in Pretender core (in a world where Pretender has a core and an ecosystem).

> your example is also the solution i suggested.

Not true. It has pieces that are similar to what you suggested, but the JSON.stringify is happening in `prepareBody`, and every one of my handlers are wrapped in a `patchableResponder`. I could rework it to use the proposed `Pretender.json`, but I wouldn't, since it doesn't gain me anything.

Specific comments aside, I agree with Trek when he says "If we lived in a world with great package managers".

It's on my todo list to move the general purpose utils I have written into its own package, but that still wouldn't be convenient for many users.

**Comment by stefanpenner** [comment]
> the basic JSON case is by far the most common. Nothing prevents apps users from taking the approach and having there own helpers to cleanup code.
> Definitely the most common, and it wouldn't be the end of the world if this got merged.

then this seems like a lot of energy, to basically say \o/.

I have lost interest – @trek :+1: / :-1: and we can move on.

**Comment by trek** [comment]
:-1: for including in the core, despite this also being my most common use case.

**Comment by stefanpenner** [comment]
sounds fine.

**Comment by trek** [comment]
:+1: on creating `pretedner-helpers` or `pretender-middlewares` especially if @samselikoff wants to generalize some things he's written

**Comment by samselikoff** [comment]
would love to chat more about this! I think I'll be ready after I finish a few more key features

**Pull request closed without merging**
