### PR TITLE
Test coverage reporting, and push report to code climate

### PR DESCRIPTION
**Pull request by mike-north**
@trek you may need to

1. Go to code climate, and get a "repo token"
2. Go to travis-ci and set up an environment variable `CC_REPO_TOKEN=<the repo token>`

At which point test coverage should be reported to code climate

### CODE REVIEW

**Comment by trek** [comment]
> Go to code climate, and get a "repo token"

Sadly this isn't available to us.

From https://codeclimate.com/docs/api

> Note: API tokens are currently only available for Code Climate organizations on paid plans.

**Comment by mike-north** [comment]
coveralls it is then

**Comment by stefanpenner** [comment]
ohya, they will make it public soon i believe.
cc @brynary

**Comment by mike-north** [comment]
screen shot 2015-08-06 at 2 05 39 pm
Seems to be working nicely now

**Comment by jonathancadepowers** [comment]
@mike-north @stefanpenner @trek 

Hey guys! Jonathan here from Code Climate. Just a heads up that our test coverage feature fully supports OSS repositories *currently*. No paid plan needed.

You actually don't need an *API* token to set this up -- instead you need a *test coverage* token. Those are two entirely different types of tokens in our app. 

Test coverage tokens are available for all OSS projects. To view this token, access the repository's **Settings** page and view the **Test Coverage** tab. Screenshot below (of a random repo):

image

Also, here's more info on how to view an OSS project's **Settings** page: http://docs.codeclimate.com/article/164-administering-open-source-repositories

Drop us a line if you run into any issues: https://codeclimate.com/help

**Comment by mike-north** [comment]
@jonathancadepowers wish I could take a look at what you're talking about but 
* I can't see the settings page, since I'm not an owner of the Pretender org
* I got @stefanpenner to try to take a look for me last week, but Code Climate didn't seem to recognize that he's an owner

**Comment by jonathancadepowers** [comment]
@mike-north Sorry about that. There are a number of different reasons why the **Settings** link may not be visible for @stefanpenner. See the troubleshooting list here: http://docs.codeclimate.com/article/164-administering-open-source-repositories#missing

Often times the culprit is GitHub third-party application restrictions being enabled, without Code Climate being whitelisted. Could that be the issue? If not, all of the other problems listed in the help doc above are also possible. Let me know which one it might be, and I'll be ready to help further.

**Comment by stefanpenner** [comment]
will take a look shortly

**Comment by stefanpenner** [comment]
it may be: 

> URI Change: If the repository's URI changes in GitHub (after its added to Code Climate), its Settings link may disappear. For example, if the project's name changes, or if the name of the GitHub user or organization that owns the repository changes (this includes casing changes). Not to worry though, as our Support Team can manually fix this issue, just let us know.

**Comment by stefanpenner** [comment]
> Often times the culprit is GitHub third-party application restrictions being enabled, without Code Climate being whitelisted. Could that be the issue?

@jonathancadepowers can you share more info on this?

**Comment by stefanpenner** [comment]
unfortunately ^ seems to be all set up correctly.. Any further thoughts?

**Comment by jonathancadepowers** [comment]
@stefanpenner Hrm. That is odd. For now I can just email you the info that you'll need to fully set up test coverage (like your test coverage token), despite this issue. I'll contact you via your @gmail.com address. In my email I'll also discuss how we can troubleshoot further on the **Settings** link not appear. Sorry again for the trouble here.

**Comment by stefanpenner** [comment]
@jonathancadepowers awesome thanks, no need for apologies. We all write software here #yolo

**Comment by trek** [comment]
@jonathancadepowers happy to temporarily add you as owner as well if you need access for figure this out.

**Comment by jonathancadepowers** [comment]
@trek That'd be great, if you don't mind.

**Comment by trek** [comment]
@jonathancadepowers  you've been invited. This project might be funky because it started out as `trek/pretender` but subsequently moved to `pretenderjs/pretender`. That's the only state I can think of that might be unaccounted for.

**Comment by jonathancadepowers** [comment]
@trek Thanks! Would you mind if I removed this repo from Code Climate, and then added it right back? I see something on my end that suggests that doing so may resolve the missing **Settings** link.

**Comment by trek** [comment]
Go for it.

**Pull request merged**
